---
booktitle: Proceedings of The 9th Conference on Robot Learning
shortname: CoRL
year: '2025'
volume: '305'
start: &1 2025-09-27
end: 2025-09-30
published: 2025-10-07
sections:
- name: Oral
  title: Oral
- name: Poster
  title: Poster
conference_number: '9'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CoRL-2025
month: 0
cycles: false
bibtex_editor: Lim, Joseph and Song, Shuran and Park, Hae-Won
editor:
- given: Joseph
  family: Lim
- given: Shuran
  family: Song
- given: Hae-Won
  family: Park
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 9th Conference on Robot Learning
    Held in Seoul, Korea on 27-30 September 2025

  Published as Volume 305 by the Proceedings of Machine Learning Research on 07 October 2025.

  Volume Edited by:
    Joseph Lim
    Shuran Song
    Hae-Won Park

  Series Editors:
    Neil D. Lawrence
date_str: 27--30 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v305"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v305
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v305
email: ''
conference:
  name: Conference on Robot Learning
  url: https://corl.org/
  location: Seoul, Korea
  dates:
  - *1
  - 2025-09-28
  - 2025-09-29
  - 2025-09-30
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: corl25_cleaned_clean.bib
# Site settings
# Original source:  corl25_cleaned_clean.bib
